name: angular-copy

on:
  push:
    branches: main
    paths:
        - docs/angular/**.html
        - docs/angular/**.css
        - docs/angular/**.js
        - docs/angular/**.png
        - docs/angular/**.ico
  workflow_dispatch:

 
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-copy.yml
    with:
      folder: angular
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
     
     
  #EOF
  
