name: angular-deploy

on:
  push:
    branches: [main/angular]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        angular_project_dir: ./angular
        github_access_token: ${{ secrets.WORKFLOW_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /azalea-contact-page/angular/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: docs/angular # The folder where your project is supposed to be after running ng build by the action.
        
        
  cleanup:
    
      runs-on: ubuntu-latest
      needs: build
      if: needs.build.result == 'success'
      
      steps:
        - name: Checkout gh-pages branch
        - uses: actions/checkout@v3
          with:
            ref: gh-pages
            
        - name: Remove old folder
          run: rm -r docs/angular || true
          
        - name: Populate new folder
          run: |
            mkdir docs/angular
            mv assets *.html *.css *.js *.txt *.png *.ico docs/angular
            
        - name: Commit and push changes to gh-pages branch
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add docs/angular
            if ! git diff-index --quiet HEAD; then
              git commit -m "Deploying to gh-pages 🚀"
              git push "https://${GITHUB_ACTOR}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages || exit 0
            fi
              
    
    
    
    
# EOF
