name: reusable-copy

on:
  workflow_call:
  
      inputs:
          folder:
            required: true
            type: string
            
      secrets:
          WORKFLOW_TOKEN:
            required: true


jobs:
  clean-and-copy:
  
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout gh-pages branch
          uses: actions/checkout@v3
          with:
            ref: gh-pages
            
        - name: Remove old files
          run: |
              git rm -r {assets,*.html,*.css,*.js,*.txt,*.png,*.ico} || true
              DIR=docs/${{ inputs.folder }}
              if test -d $DIR; then
                git rm -r $DIR*
              fi
              
        - name: Sparse checkout docs/${{ inputs.folder }} folder of the main branch
          run: |
              mkdir temp
              cd temp
              git clone \
              --depth 1 \
              --filter=blob:none \
              --sparse \
              "https://${GITHUB_ACTOR}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${GITHUB_REPOSITORY}" \
              ;
              cd ${{ github.event.repository.name }}
              git sparse-checkout init --cone
              git sparse-checkout set docs/${{ inputs.folder }}/*
              cd docs
              mv ${{ inputs.folder }}/* ../../../docs/${{ inputs.folder }}/*
              
        - name: Commit and push changes to the gh-pages branch
          run: |
              git config user.name "${GITHUB_ACTOR}"
              git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              timestamp=$(date -u)
              git add ${{ inputs.folder }}/*
              if ! git diff-index --quiet HEAD; then
                git commit -m "Auto deployment on push to docs/${{ inputs.folder }} on [${timestamp}]"
                git push "https://${GITHUB_ACTOR}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages || exit 0
              fi
 


#EOF
  
