name: reusable-copy

on:
  workflow_call:
  
      inputs:
          folder:
            required: true
            type: string
            
      secrets:
          WORKFLOW_TOKEN:
            required: true


jobs:
  clean-and-copy:
  
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout gh-pages branch
          uses: actions/checkout@v3
          with:
            ref: gh-pages
            path: ./gh-pages
            fetch-depth: 1
            
        - name: Remove old files
          run: |
              cd gh-pages || true
              cd ${{ github.event.repository.name }} || true
              git rm -r {assets,*.html,*.css,*.js,*.txt,*.png,*.ico} || true
              DIR=docs/${{ inputs.folder }}
              if test -d $DIR; then
                git rm -r $DIR*
              fi
              
        - name: Checkout main branch
          uses: actions/checkout@v3
          with:
            ref: main
            path: ./main
            fetch-depth: 1
            
        - name: Move new files to gh-pages branch
          run: |
              pwd
              ls
              echo "Entering main dir"
              cd main || true
              pwd
              ls
              echo "Entering docs dir"
              cd docs
              pwd
              ls
              echo "Moving ${{ inputs.folder }}"
              mv ${{ inputs.folder }}/* \
              ../../gh-pages/docs
              cd ../../gh-pages/docs
              
        - name: Commit and push changes to the gh-pages branch
          run: |
              pwd
              git config user.name "${GITHUB_ACTOR}"
              git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              timestamp=$(date -u)
              git add ${{ inputs.folder }}/*
              if ! git diff-index --quiet HEAD; then
                git commit -m "Auto deployment on push to docs/${{ inputs.folder }} on [${timestamp}]"
                git push "https://${GITHUB_ACTOR}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages || exit 0
              fi
 



#EOF


  
