name: vanilla-copy

on:
  push:
    branches: main
    paths: 
        - docs/mvp/**.html
        - docs/mvp/**.css
        - docs/mvp/**.js
        - docs/mvp/**.png
        - docs/mvp/**.ico
  workflow_dispatch:

 
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-copy.yml
    with:
      folder: mvp
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
     
     
  #EOF
  
